### ISSUE TITLE
3.1 not working in nodejs 20.7

### ISSUE THREAD

**Issue by lucienimmink** [maugenst/zip-a-folder#50]
Getting this error
```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'xxx\node_modules\zip-a-folder\dist\lib\mjs\ZipAFolder' imported from xxx\node_modules\zip-a-folder\dist\lib\mjs\index.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:224:11)
    at moduleResolve (node:internal/modules/esm/resolve:836:10)
    at defaultResolve (node:internal/modules/esm/resolve:1034:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:375:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:344:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  url: URL {},
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.7.0
```

Shouldn't these be imported with the file extension?

**Comment by maugenst** [comment]
Please have a look in the answer here: https://stackoverflow.com/a/68783000

At least I cannot see a way to automatically add extensions for imports via transpiler options: 
* swc: https://github.com/swc-project/swc/issues/5346
* tsc: https://github.com/microsoft/TypeScript/pull/35148

For the time being this seems to be just solveable via adding `--experimental-specifier-resolution=node`.

**Comment by maugenst** [comment]
But you are right ... I changed the modules file extension mjs file extension to mjs. Plese rebase to 3.1.1 

Nonetheless this didn't solve the problem that the transpiled aren't referring the imports to either mjs or js files. I cannot see how this can be overcome so far ...

**Comment by maugenst** [comment]
Found a nice little solution for the problem. So far I cannot see a solution for the overall problem that file imports MUST have valid extensions, but this is out of the scope here. 
Feel free to upgrade to 3.1.2.
